
import { GoogleGenAI } from "@google/genai";
import { MODEL_NAME } from "../constants";
import { AIResponse, AspectRatio } from "../types";

export const editWithAI = async (
  base64Image: string,
  prompt: string,
  aspectRatio: AspectRatio = "1:1"
): Promise<AIResponse> => {
  try {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    
    // Clean base64 string
    const base64Data = base64Image.split(',')[1];
    const mimeType = base64Image.match(/data:(.*?);/)?.[1] || 'image/png';

    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Data,
              mimeType: mimeType,
            },
          },
          {
            text: `Please edit this image following these instructions: ${prompt}. Output the edited image.`,
          },
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: aspectRatio
        }
      }
    });

    let imageUrl = '';
    let text = '';

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        imageUrl = `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
      } else if (part.text) {
        text = part.text;
      }
    }

    if (!imageUrl) {
      throw new Error("No image was returned from the AI.");
    }

    return { imageUrl, text };
  } catch (error: any) {
    console.error("AI Edit Error:", error);
    return {
      imageUrl: '',
      error: error?.message || "An unexpected error occurred while processing your image."
    };
  }
};

export const generateImage = async (
  prompt: string,
  aspectRatio: AspectRatio = "1:1"
): Promise<AIResponse> => {
  try {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    
    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: {
        parts: [
          {
            text: `Generate an image based on this description: ${prompt}`,
          },
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: aspectRatio
        }
      }
    });

    let imageUrl = '';
    let text = '';

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        imageUrl = `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
      } else if (part.text) {
        text = part.text;
      }
    }

    if (!imageUrl) {
      throw new Error("No image was generated by the AI.");
    }

    return { imageUrl, text };
  } catch (error: any) {
    console.error("AI Generation Error:", error);
    return {
      imageUrl: '',
      error: error?.message || "An unexpected error occurred while generating your image."
    };
  }
};

export const chatWithAI = async (
  message: string,
  history: { role: "user" | "model"; parts: { text: string }[] }[] = []
): Promise<{ text: string; error?: string }> => {
  try {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    const chat = ai.chats.create({
      model: "gemini-3-flash-preview",
      config: {
        systemInstruction: "You are a helpful assistant integrated into Nano-Kubana, a photo editing app. You can help users with editing tips, creative ideas, or general questions.",
      },
      history: history,
    });

    const response = await chat.sendMessage({ message });
    return { text: response.text || "" };
  } catch (error: any) {
    console.error("AI Chat Error:", error);
    return {
      text: "",
      error: error?.message || "An unexpected error occurred during the chat."
    };
  }
};
